cryptomanager/app/transactions/views.py
# Import functionalities from FLASK
from flask import Blueprint, render_template, redirect, url_for, flash, g
# Import functionalities from FLASK Login
from flask_login import login_required, current_user
# Import database models
from ..models import Transactions, Assets
# Import forms
from .forms import TransactionForm
# Import datetime to handle dates
import datetime
# Import the api to make calls
from ...app import api


transactions = Blueprint('transactions', __name__, template_folder="templates")


@transactions.route('/transactions', methods=["GET", "POST"])
@login_required
def get_transactions():
    if not current_user:
        redirect(url_for('auth.login'))
        flash("You need to be logged in for this functionality", "error")
    transactions = []

    # Get transactions
    try:
        db_transactions = Transactions.objects.filter(userid=current_user.id)
        for transaction in db_transactions:
            transactions.append(transaction)
    except Transactions.DoesNotExist:
        transactions = None

    return render_template('transactions.html', transactions=transactions)


@transactions.route('/add_transaction', methods=["GET", "POST"])
@login_required
def add_transaction():
    if not current_user:
        redirect(url_for('auth.login'))
        flash("You need to be logged in for this functionality", "error")
    g.user = current_user
    form = TransactionForm()
    form.vs_currency.choices = get_currencies()

    if form.validate_on_submit():
        volume = form.volume.data
        coin_symbol = form.coin_symbol.data
        vs_currency = form.vs_currency.data
        prize = form.prize.data
        ordertype = form.ordertype.data
        usd_prize = float(form.usd_prize.data)

        assetOut = g.asset
        assetIn = coin_symbol if ordertype == "BUY" else vs_currency

        # update asset out
        assetOut_amount = (assetOut.amount - prize if ordertype == "BUY"
                           else assetOut.amount - volume)
        if assetOut_amount > 0:
            Assets.objects(userid=current_user.id,
                           asset_name=assetOut.asset_name).update_one(
                           set__amount=assetOut_amount)
        else:
            Assets.objects(userid=current_user.id,
                           asset_name=assetOut.asset_name).delete()

        # Update or save assset in
        try:
            # Asset exists
            assetIn_db = Assets.objects.get(
                    userid=current_user.id, asset_name=assetIn)
            assetIn_amount = (assetIn_db.amount + volume if ordertype == "BUY"
                              else assetIn_db.amount + prize)
            if assetIn == "USD":
                Assets.objects(userid=current_user.id,
                               asset_name=assetIn).update_one(
                               set__amount=assetIn_amount, upsert=False)
            else:
                costs = (((assetIn_db.costs * assetIn_db.amount) +
                          (usd_prize * volume if ordertype == "BUY"
                          else usd_prize * prize))/assetIn_amount)
                Assets.objects(userid=current_user.id,
                               asset_name=assetIn).update_one(
                               set__amount=assetIn_amount, set__costs=costs,
                               upsert=False)
        except Assets.DoesNotExist:
            # Asset doesnt exist
            if assetIn == "USD":
                new_asset = Assets(userid=current_user.id, asset_name=assetIn,
                                   amount=(volume if ordertype == "BUY"
                                           else prize))
            else:
                new_asset = Assets(userid=current_user.id, asset_name=assetIn,
                                   amount=(volume if ordertype == "BUY"
                                           else prize), costs=usd_prize)
            new_asset.save()

        transaction = Transactions(userid=current_user.id,
                                   date=datetime.datetime.now(),
                                   ordertype=ordertype.lower(),
                                   volume=volume,
                                   coin_symbol=coin_symbol,
                                   vs_currency=vs_currency,
                                   prize=(prize/volume),
                                   costs=prize)
        transaction.save()
        return redirect(url_for('transactions.get_transactions'))

    return render_template('add_transaction.html', form=form)


def get_currencies():
    """
        param: none
        Method to filter the fiat currencies out of vs_currencies except USD
    """
    exclude_fiat = ["aed", "ars", "aud", "bdt", "bmd",  "bhd", "brl", "cad",
                    "chf", "clp", "cny", "czk", "dkk", "eur", "gbp", "hkd",
                    "huf", "idr", "ils", "inr", "jpy", "krw", "kwd", "lkr",
                    "mmk", "mxn", "myr", "ngn", "nok", "nzd", "php", "pkr",
                    "pln", "rub", "sar", "sek", "sgd", "thb", "try", "twd",
                    "uah", "vef", "vnd", "zar"]
    return ([y.upper() for y in api.supported_vs_currency if
            [x for x in api.supported_coins]
            and y not in exclude_fiat])

cryptomanager/app/transactions/templates/add_transaction.html
{% extends 'base.html' %}
{% block heading %}{{ ('Transactions') }}{% endblock %}
{% from '_error_messages.html' import error_messages %}
{% set active_page = 'transactions' %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/add-transaction.css')}}" type="text/css">
{% endblock %}

{% block content %}

<div class="jumbotron text-center">
    <h5>Manage your transaction</h5>
</div>

<div class="form">
    <form method="POST" action="{{ url_for('transactions.add_transaction') }}">
        {{ form.csrf_token }}
        {{ form.usd_prize }}
        {{ error_messages(form.errors) }}
        <div class="row">
            <div class="col-12 col-md-4">
                <strong>{{ form.ordertype.label() }}</strong>
                {{ form.ordertype(class='m-3 selectpicker', **{'data-live-search': 'true'}) }}
            </div>
            <div class="col-12 col-md-4">
                <strong>{{ form.coin_symbol.label() }}</strong>
                {{ form.coin_symbol(class='m-3 selectpicker', **{'data-live-search': 'true'}) }}
            </div>

            <div class="col-12 col-md-4">
                <strong>{{ form.vs_currency.label() }}</strong>
                {{ form.vs_currency(class='m-3 selectpicker', **{'data-live-search': 'true'}) }}
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                {{ form.volume.label }}
                {{ form.volume(class='m-3', value='0') }}
            </div>

            <div class="col-12 col-md-6">
                {{ form.prize.label}}
                {{ form.prize(value='0', class='m-3') }}
            </div>
        </div>
        <div class="form-group d-flex justify-content-center">
            <a href="{{ url_for('transactions.get_transactions') }}" class="btn btn-danger col-md-3 m-2 m-md-4">Back</a>
            <button type="submit" id="submit-button" class="btn btn btn-dark col-md-3 m-2 m-md-4" disabled>Submit</button>
          </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script  type="text/javascript" src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/add-transaction.js')}}"></script>
{% endblock %}

cryptomanager/app/transactions/templates/transactions.html
{% extends 'base.html' %}
{% block heading %}{{ ('Transactions') }}{% endblock %}
{% set active_page = 'transactions' %}

{% block styles %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/assets-transactions.css')}}" type="text/css">
{% endblock %}

{% block content %}

<div class="jumbotron text-center">
    <h5>Transactions overview</h5>
    <a class="btn btn-lg btn-success mt-5"href="{{ url_for('transactions.add_transaction') }}">Add transaction</a>
</div>

<div class="justify-content-center">
<div class="table-responsive col-md-12">
    <table id="table" class="table table-striped">
        <thead>
            <tr>
                <th data-field="Date" data-sortable="true" scope="col">Date</th>
                <th data-field="Ordertype" data-sortable="true" scope="col">Ordertype</th>
                <th data-field="Pair" scope="col">Pair</th>
                <th class="d-none d-sm-block" data-field="Price" scope="col">Rate</th>
                <th data-field="Volume" scope="col">Volume</th>
                <th data-field="Cost" scope="col">Costs</th>
            </tr>
        </thead>
        <tbody>
            {% if transactions %}
                {% for transaction in transactions %}
                    {% if transaction.ordertype == 'deposit' or transaction.ordertype == 'withdrawal'%}
                        <tr>
                            <td scope="row">{{ transaction.date | date}}</td>
                            <td class="{{ transaction.ordertype }}">{{ transaction.ordertype | capitalize}}</td>
                            <td>-</td>
                            <td class="d-none d-sm-block">-</td>
                            <td>{{transaction.volume}}</td>
                            <td>-</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td scope="row">{{ transaction.date | date }}</td>
                            <td class="{{ transaction.ordertype }}">{{ transaction.ordertype | capitalize}}</td>
                            <td>{{ transaction.coin_symbol }}/{{ transaction.vs_currency }}</td>
                            <td class="d-none d-sm-block">{{ transaction.prize }} <strong>{{ transaction.coin_symbol }}/{{ transaction.vs_currency }}</strong></td>
                            <td>{{transaction.volume}}</td>
                            <td>{{ transaction.costs }} {{ transaction.vs_currency }} </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/transactions.js')}}"></script>
{% endblock %}