cryptomanager/app/assets/views.py
# Import functionalities from FLASK
from flask import Blueprint, render_template, flash, redirect, url_for, g
# Import functionalities from FLASK Login
from flask_login import login_required, current_user
# Import forms
from .forms import DepositForm
# Import database models
from ..models import Assets, User, Transactions
# Import api
from ...app import api
# Import json to handle json data
import json
# Import datetime to handle dates
import datetime

assets = Blueprint('assets', __name__, template_folder="templates")


@assets.route('/assets', methods=["GET", "POST"])
@login_required
def get_asset():
    if not current_user:
        redirect(url_for('auth.login'))
        flash("You need to be logged in for this functionality", "error")
    g.user = current_user
    form = DepositForm()
    list_assets = []
    current_value = 0
    completed_assets_list = []
    withdrawable_balance = 0

    try:
        db_assets = Assets.objects.filter(userid=current_user.id)
        for asset in db_assets:
            list_assets.append(asset)
    except Assets.DoesNotExist:
        list_assets = None
    if list_assets:
        usd_balance = next(
            (x for x in list_assets if x.asset_name == "USD"), None)
        if usd_balance:
            withdrawable_balance = usd_balance.amount
            list_assets.remove(usd_balance)
        updated_list_assets = api.retrieve_current_prizes(
                                                        '/simple/price',
                                                        list_assets)
        completed_assets_list = Assets.calculate_profits(updated_list_assets)
        current_value = (Assets.calculate_current_value(completed_assets_list)
                         + withdrawable_balance)

    if form.validate_on_submit():
        transaction_type = form.transaction_type.data.lower()
        amount = form.amount.data
        if transaction_type == 'deposit':
            withdrawable_balance = g.value
            current_value += amount
        else:
            withdrawable_balance = g.value
            current_value -= amount
        if withdrawable_balance == 0:
            Assets.objects(userid=g.user.id, asset_name='USD').delete()
        else:
            Assets.objects(userid=g.user.id, asset_name='USD').update_one(
                            set__amount=withdrawable_balance, upsert=True)
        transaction = Transactions(userid=g.user.id,
                                   date=datetime.datetime.now(),
                                   ordertype=transaction_type, volume=amount)
        transaction.save()

    return render_template('assets.html', form=form,
                           assets=completed_assets_list,
                           withdrawable_balance=withdrawable_balance,
                           current_value=current_value)


@assets.route('/fetch_owned_assets', methods=["GET"])
@login_required
def fetch_owned_assets():
    """
    param: none:
        Method to forward the owned assets to the frontend
    """
    try:
        db_assets = Assets.objects.filter(userid=current_user.id)
        return db_assets.to_json()
    except Assets.DoesNotExist:
        return None


@assets.route('/fetch_supported_assets', methods=["GET"])
@login_required
def fetch__supported_assets():
    """
    param: none:
        Method to forward the supported coins to the frontend
    """
    return json.dumps(api.supported_coins)

cryptomanager/app/general/views.py
# Import functionalities from FLASK
from flask import Blueprint, render_template, url_for, redirect
# Import functionalities from FLASK login
from flask_login import current_user, login_required, login_user, logout_user
#  Import database model
from ..models import User

general = Blueprint("general", __name__)


@general.route("/")
@general.route("/home")
def home():
    if current_user.is_authenticated:
        return redirect(url_for('assets.get_asset'))
    return render_template("welcomescreen.html")

cryptomanager/app/leaderboard/views.py
# Import functionalities from FLASK
from flask import Blueprint, render_template
# Import functionalities from FLASK login
from flask_login import current_user
# Import datebase models
from ..models import Assets, User
# Import api to make api calls
from ...app import api

leaderboard = Blueprint('leaderboard', __name__, template_folder='templates')


@leaderboard.route('/leaderboard')
def get_leaderboard():
    user = None
    if current_user:
        this_user = current_user
    leaderboard_data = []

    # Get all users
    users = User.objects().only('id', 'firstname')
    # Get all assets owned by all users distinct
    assets_names = [x.lower() for x in Assets.objects().distinct(
                                field="asset_name") if x != "USD"]
    assets_querystring = ",".join(getid_list(assets_names))
    # Get the current prices
    prices = api.retrieve_current_prize('/simple/price', assets_querystring)

    for user in users:
        usd_balance = 0
        list_assets = []
        updated_list_assets = []
        try:
            db_assets = Assets.objects.filter(userid=user.id)
            for asset in db_assets:
                list_assets.append(asset)
        except Assets.DoesNotExist:
            list_assets = None
        if list_assets:
            usd_balance = next(
                (x for x in list_assets if x.asset_name == "USD"), None)
        if usd_balance:
            list_assets.remove(usd_balance)
        for asset in list_assets:
            asset.prize = (prices["".join(get_id(asset.asset_name.lower()))]
                           ['usd'])
        updated_list_assets = Assets.calculate_profits(list_assets)
        user_info = LeaderboardUser(user=user, assets=updated_list_assets,
                                    usd_balance=usd_balance)
        # Get the percentage of the asset
        user_info.calculate_assets_percentage()
        # Calculate total profit of user
        user_info.calculate_total_profit()
        # Append to leaderboard data
        leaderboard_data.append(user_info)
    leaderboard_data.sort(key=sort_criteria, reverse=True)

    return render_template('leaderboard.html',
                           leaderboard_data=leaderboard_data[:10],
                           user=this_user,
                           counter=0)


class LeaderboardUser:
    """ API class

    Methods:
        def calculate_assets_percentage:
            param: none
        Method to calculate how much of the portfolio is a specific
        asset in percentage

        calculate_total_profit:
            param: none
        Method to calculate total profit per user
    """
    def __init__(self, user, assets, usd_balance):
        self.user = user
        self.assets = assets
        self.usd_balance = usd_balance

    def calculate_assets_percentage(self):
        total_value = (sum([(x.prize * x.amount) for x in self.assets])
                       + self.usd_balance.amount
                       if self.usd_balance
                       else sum([(x.prize * x.amount) for x in self.assets]))
        if self.usd_balance:
            self.usd_balance.percentage = (self.usd_balance.amount /
                                           total_value) * 100
        for asset in self.assets:
            asset.percentage = ((asset.prize * asset.amount) /
                                total_value) * 100

    def calculate_total_profit(self):
        self.user.total_profit = sum([x.p_l for x in self.assets])


def sort_criteria(e):
    """
        param: leaderboard data
        Helper to get the sorting key
    """
    return e.user.total_profit


def getid_list(assets):
    """
        param: list of asset
        Helper to get the id of the coin in order to call the API
    """
    return [x['id'] for x in api.supported_coins if x['symbol'] in assets]


def get_id(assets):
    """
        param: asset
        Helper to get the id of the coin in order to get specific
        data from API response
    """
    return [x['id'] for x in api.supported_coins if x['symbol'] == assets]

cryptomanager/app/templates/_error_messages.html
{% macro error_messages(errors) %}
{% if errors %}
<div class="alert alert-danger">
  {% for field in errors %}
    <b>{{ field | capitalize }} field has following errors:</b><br>
    {% for error in errors[field] %}
    {{ error }}<br>
    {% endfor %}
  {% endfor %}
</div>
{% endif %}
{% endmacro %}

cryptomanager/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}" type="text/css">
    {% block styles %}
    {% endblock %}
    <title>Crypto Portfolio</title>
</head>

<body>
    <div class="overflow">
    
    <header>
        <nav id="navbar" class="navbar navbar-expand-md navbar-dark bg-dark">
            {% if current_user.is_authenticated %}
                <a class="navbar-brand" href="{{ url_for('assets.get_asset') }}"><i class="fas fa-user"></i> {{ current_user.firstname | capitalized }}</a>
            {% else %}
                <a class="navbar-brand" href="{{ url_for('general.home') }}">Welcome</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'home' }}" href="{{ url_for('general.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'leaderboard' }}" href="{{ url_for('leaderboard.get_leaderboard') }}">Leaderboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'login' }}" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'register' }}" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'leaderboard' }}" href="{{ url_for('leaderboard.get_leaderboard') }}">Leaderboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'assets' }}" href="{{ url_for('assets.get_asset') }}">Assets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'transactions' }}" href="{{ url_for('transactions.get_transactions') }}">Transactions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if active_page == 'manage account' }}" href="{{ url_for('auth.manage') }}">Manage Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        <div class="row">
            <div class="col">
                <h1 class="text-center mt-3">{% block heading %}{% endblock %}</h1>
            </div>
        </div>
        <section id="flashes" class="row justify-content-center" >
            <div class="col-10 text-center">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <p class="{{ category }}">{{ message }}</p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            </div>
        </section>
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js')}}"></script>

    {% block scripts %}
    {% endblock %}
</div>

</body>

</html>

cryptomanager/app/templates/error.html
{% extends 'base.html' %}
{% block heading %}{{ ('Error') }}{% endblock %}
{% set active_page = 'home' %}

{% block styles %}
     <link rel="stylesheet" href="{{ url_for('static', filename='css/login-register.css')}}" type="text/css">
{% endblock %}



{% block content %}
<div class="background"></div>
<div class="text-center row">
    <div class="form col-md-8 offset-md-2">
    <h5 class="my-3">Something went wrong, excuses for the inconvience</h5>
</div>
</div>
{% endblock %}

cryptomanager/app/templates/login.html
{% extends 'base.html' %}
{% block heading %}{{ ('Login') }}{% endblock %}
{% from '_error_messages.html' import error_messages %}
{% set active_page = 'login' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login-register.css')}}" type="text/css">
{% endblock %}


{% block content %}
<div class="background"></div>
<div id="content" class="row justify-content-center align-items-center">
  <div class="col-10 col-md-6 form">
    
    <form method="POST" action="{{ url_for('login') }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        <div class="d-none d-sm-block">{{ form.email.label }}</div>
        {{ form.email(class="form-control", placeholder="Email") }}
      </div>
      <div class="form-group">
        <div class="d-none d-sm-block">{{ form.password.label }}</div>
        {{ form.password(class="form-control", placeholder="Password") }}
      </div>
      <div class="form-group d-flex justify-content-center">
        <button id="clear-button" class="btn btn-outline-dark col-md-3 m-2 m-md-4" disabled>Clear</button>
        <button type="submit" id="submit-button" class="btn btn btn-dark col-md-3 m-2 m-md-4" disabled>Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/validation-login.js')}}"></script>
{% endblock %}

cryptomanager/app/templates/register.html
{% extends 'base.html' %}
{% block heading %}{{ ('Register') }}{% endblock %}
{% from '_error_messages.html' import error_messages %}
{% set active_page = 'register' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login-register.css')}}" type="text/css">
{% endblock %}


{% block content %}
<div class="background"></div>
<div id="content" class="row justify-content-center align-items-center">
  <div class="col-10 col-md-6 form">

    <form method="POST" action="{{ url_for('register') }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        <div class="d-none d-sm-block">{{ form.firstname.label }}</div>
        {{ form.firstname(class="form-control", placeholder="Firstname") }}
      </div>
      <div class="form-group">
        <div class="d-none d-sm-block">{{ form.email.label }}</div>
        {{ form.email(class="form-control", placeholder="Email") }}
      </div>
      <div class="form-group">
        <div class="d-none d-sm-block">{{ form.password.label }}</div>
        {{ form.password(class="form-control", placeholder="Password") }}
      </div>
      <div class="form-group">
        <div class="d-none d-sm-block">{{ form.password_confirm.label }}</div>
        {{ form.password_confirm(class="form-control", placeholder="Confirm password") }}
      </div>
      <div class="form-group d-flex justify-content-center">
        <button id="clear-button" class="btn btn-outline-dark col-md-3 m-2 m-md-2" disabled>Clear</button>
        <button type="submit" id="submit-button" class="btn btn btn-dark col-md-3 m-2 m-md-2" disabled>Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/validation-register.js')}}"></script>
{% endblock %}

cryptomanager/app/templates/welcomescreen.html
{% extends 'base.html' %}
{% block heading %}{{ ('Crypto Portfolio Manager') }}{% endblock %}
{% set active_page = 'home' %}

{% block styles %}
     <link rel="stylesheet" href="{{ url_for('static', filename='css/login-register.css')}}" type="text/css">
{% endblock %}



{% block content %}
<div class="background"></div>
<div class="text-center row">
    <div class="form col-md-8 offset-md-2">
    <h5 class="my-3">The one and only way to succesfull manage your Crypto Portfolio</h5>
    <a class="btn btn-outline-secondary btn-lg my-3" href="{{ url_for('auth.register')}}" role="button">Register now!</a>
    <hr class="my-3>">
    <p>Already signed up?</p>
    <a class="btn btn-outline-dark" href="{{ url_for('auth.login')}}" role="button">Login</a>
</div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/main.js')}}"></script>
<script>setElementListener()</script>
{% endblock %}