cryptomanager/app/assets/forms.py
# Imports from FLASK
from flask import g, flash
# Extension for implementing WTForms for managing web forms
from flask_wtf import FlaskForm
# Import fields from WTForms
from wtforms.fields import FloatField, HiddenField
# Import validators from WTForms
from wtforms.validators import InputRequired, DataRequired, ValidationError
# Import database model
from ..models import Assets


class DepositForm(FlaskForm):
    """Class DepositForm

    Attributes:
        amount: The amount which the user want to deposit or withdrawal

    Methods:
        validate_amount:
            param: amount field
        Method to check whether the user have sufficient amount to withdrawal
    """

    amount = FloatField(("Amount"),
                        validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!")
    ])
    transaction_type = HiddenField()

    @staticmethod
    def validate_amount(form, field):
        try:
            available_asset = Assets.objects.get(userid=g.user.id,
                                                 asset_name='USD')
        except Assets.DoesNotExist:
            if (form.transaction_type.data == 'withdrawal'):
                flash("Insufficient funds to withdraw", "error")
                raise ValidationError()
            g.value = field.data
            flash("{} is added to your deposit".format(field.data), "success")
            return
        if (form.transaction_type.data == 'withdrawal'):
            if field.data > available_asset.amount:
                flash("Insufficient funds to withdraw", "error")
                raise ValidationError()
            g.value = available_asset.amount - field.data
            flash("{} is withdrawn from your deposit".format(field.data),
                  "success")
            return
        g.value = available_asset.amount + field.data
        flash("{} is added to your deposit".format(field.data), "success")
        return

cryptomanager/app/assets/views.py
# Import functionalities from FLASK
from flask import Blueprint, render_template, flash, redirect, url_for, g
# Import functionalities from FLASK Login
from flask_login import login_required, current_user
# Import forms
from .forms import DepositForm
# Import database models
from ..models import Assets, User, Transactions
# Import api
from ...app import api
# Import json to handle json data
import json
# Import datetime to handle dates
import datetime

assets = Blueprint('assets', __name__, template_folder="templates")


@assets.route('/assets', methods=["GET", "POST"])
@login_required
def get_asset():
    if not current_user:
        redirect(url_for('auth.login'))
        flash("You need to be logged in for this functionality", "error")
    g.user = current_user
    form = DepositForm()
    list_assets = []
    current_value = 0
    completed_assets_list = []
    withdrawable_balance = 0

    try:
        db_assets = Assets.objects.filter(userid=current_user.id)
        for asset in db_assets:
            list_assets.append(asset)
    except Assets.DoesNotExist:
        list_assets = None
    if list_assets:
        usd_balance = next(
            (x for x in list_assets if x.asset_name == "USD"), None)
        if usd_balance:
            withdrawable_balance = usd_balance.amount
            list_assets.remove(usd_balance)
        updated_list_assets = api.retrieve_current_prizes(
                                                        '/simple/price',
                                                        list_assets)
        completed_assets_list = Assets.calculate_profits(updated_list_assets)
        current_value = (Assets.calculate_current_value(completed_assets_list)
                         + withdrawable_balance)

    if form.validate_on_submit():
        transaction_type = form.transaction_type.data.lower()
        amount = form.amount.data
        if transaction_type == 'deposit':
            withdrawable_balance = g.value
            current_value += amount
        else:
            withdrawable_balance = g.value
            current_value -= amount
        if withdrawable_balance == 0:
            Assets.objects(userid=g.user.id, asset_name='USD').delete()
        else:
            Assets.objects(userid=g.user.id, asset_name='USD').update_one(
                            set__amount=withdrawable_balance, upsert=True)
        transaction = Transactions(userid=g.user.id,
                                   date=datetime.datetime.now(),
                                   ordertype=transaction_type, volume=amount)
        transaction.save()

    return render_template('assets.html', form=form,
                           assets=completed_assets_list,
                           withdrawable_balance=withdrawable_balance,
                           current_value=current_value)


@assets.route('/fetch_owned_assets', methods=["GET"])
@login_required
def fetch_owned_assets():
    """
    param: none:
        Method to forward the owned assets to the frontend
    """
    try:
        db_assets = Assets.objects.filter(userid=current_user.id)
        return db_assets.to_json()
    except Assets.DoesNotExist:
        return None


@assets.route('/fetch_supported_assets', methods=["GET"])
@login_required
def fetch__supported_assets():
    """
    param: none:
        Method to forward the supported coins to the frontend
    """
    return json.dumps(api.supported_coins)

cryptomanager/app/assets/templates/assets.html
{% extends 'base.html' %}
{% block heading %}{{ ('Assets') }}{% endblock %}
{% set active_page = 'assets' %}

{% block styles %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/assets-transactions.css')}}" type="text/css">
{% endblock %}

{% block content %}

<div class="jumbotron text-center">
    <p>Withdrawable balance: <strong>{{ withdrawable_balance | trim }}</strong> USD </p>
    <p>Current value: <strong>{{ current_value | trim}}</strong> USD </p>
    <button id="deposit" class="btn btn-success m-2" data-toggle="modal" data-target="#depositModal" data-backdrop="static" data-keyboard="false" onclick="setTransactionType('deposit')">Deposit</button>
    <button id="withdrawal" class="btn btn-danger m-2" data-toggle="modal" data-target="#depositModal" data-backdrop="static" data-keyboard="false" onclick="setTransactionType('withdrawal')">Withdrawal</button>
    <div class="my-2 my-md-4"></div>
</div>
<div class="justify-content-center">
<div class="table-responsive col-md-12">
    <table id="table" class="table table-striped">
        <thead>
            <tr>
                <th data-field="Asset" data-sortable="true" scope="col">Asset</th>
                <th data-field="Amount" data-sortable="true" scope="col">Amount</th>
                <th class="d-none d-sm-block" data-field="Price" data-sortable="true" scope="col">Rate</th>
                <th class="d-none d-sm-block" data-field="Value" data-sortable="true" scope="col">Value (USD)</th>
                <th data-field="P/L" data-sortable="true" scope="col">P/L</th>
            </tr>
        </thead>
        <tbody>
                {% if assets %}
                {% for asset in assets %}
                <tr>
                    <td scope="row"><img src=""> {{ asset.asset_name }}</td>
                    <td>{{ asset.amount }}</td>
                    <td class="d-none d-sm-block">{{ (asset.costs) | trim }} <strong>{{ asset.asset_name }}/USD</strong></td>
                    <td class="d-none d-sm-block">{{ (asset.prize * asset.amount) | trim }}</td>
                    {% if asset.p_l < 0 %}
                        <td style="color: red;">{{ asset.p_l | trim}}%</td>
                    {% else %}  
                        <td style="color: green;">{{ asset.p_l | trim}}%</td>
                    {% endif %}
                </tr>
                {% endfor %}
                {% endif %}
            </tr>
        </tbody>
    </table>
    </div>
</div>

<div class="modal fade" id="depositModal" tabindex="-1" role="dialog" aria-labelledby="depositModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="depositModalLabel">Deposit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form col-12 col-md-8" action="{{ url_for('assets.get_asset') }}" method="POST">
                        <div class="row justify-content-end">
                            <div class="input-group has-validation mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>
                                {{ form.csrf_token }}
                                {{ form.transaction_type(id="transaction_type") }}
                                {{ form.amount(class="form-control", placeholder="Enter your amount", id="amount") }}
                                    <div id="validationAmountFeedback" class="invalid-feedback">
                                        Please enter a number
                                    </div>
                            </div>
                           <button id="clear-button" class="btn btn-outline-dark m-2" disabled>Clear</button>
                            <button id="submit-button" type="submit" class="btn btn-dark m-2" disabled>Confirm</button>   
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/assets.js')}}"></script>
{% endblock %}